### ISSUE TITLE
Example of how to pass in config object instead of specify "configFile"

### ISSUE THREAD

**Issue by prettycode** [karma-runner/gulp-karma#13]
I don't see an example of how, in a gulpfile.js, to pass in a config settings object into a karma server. For example, I'm using this:

    karma.start({
        configFile: __dirname + '/karma.conf.js',
        singleRun: true
    });

But instead, I want to pass in an object defined in my gulpfile.js.

It makes sense not to use a karma.conf.js file in my case because the `files` property in the config contains values that are variables in gulpfile.js.

**Comment by pkozlowski-opensource** [comment]
@prettycode actually it is pretty easy - just pass the complete config object to the `start` method. In fact this repo used to illustrate exactly this setup (see https://github.com/karma-runner/gulp-karma/blob/3b39f2e4cafbb6edca9ff9ac4150b76becc85f82/gulpfile.js) but it turned out that many people expected to see the setup with an external file.

Does it answer your question?

**Comment by prettycode** [comment]
Wow, thanks for the quick response! Sweet, that's easy. I was overthinking it. Thank you, good sir!
